title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
remote_theme : mmistakes/minimal-mistakes
url                      : "https://jeonhun6084.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/yunhee" # the subpath of your site, e.g. "/blog"
